var
quantidadeSeries : inteiro
nomeExercicio : caractere
nomeCliente : caractere
contador : inteiro


escreva("informe o seu nome")
leia(nomeCliente)
escreva("informe a quantidade de séries que deseja fazer")
leia(quantidadeSeries)
escreva("Informe o nome do seu Exercício")
leia(nomeExercicio)


para quantidadeSeries de 1 ate quantidadeSeries passo +1 faca
    escreval (NomeCliente + "sua repetição do exercício " + nomeExercicio + quantidadeSeries)
    
fimpara
